# Generated by Django 5.1.8 on 2025-04-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="th_chat_id",
            new_name="tg_chat_id",
        ),
    ]
